import type { QuestionnaireStep } from '@/types/questionnaire';

/**
 * Sample questionnaire data demonstrating all question types
 * This will be replaced with data from your API/database
 */
export const questionnaireSteps: QuestionnaireStep[] = [
  {
    id: 1,
    title: 'Personal Information',
    description: 'Tell us about yourself',
    questions: [
      {
        type: 'short-text',
        id: 'firstName',
        question: 'What is your first name?',
        required: true,
        placeholder: 'John',
        onChange: () => {},
      },
      {
        type: 'short-text',
        id: 'lastName',
        question: 'What is your last name?',
        required: true,
        placeholder: 'Doe',
        onChange: () => {},
      },
      {
        type: 'email',
        id: 'email',
        question: 'What is your email address?',
        description: 'We will use this to contact you',
        required: true,
        onChange: () => {},
      },
      {
        type: 'phone',
        id: 'phone',
        question: 'What is your phone number?',
        required: true,
        onChange: () => {},
      },
    ],
  },
  {
    id: 2,
    title: 'Background Information',
    description: 'Help us understand your situation',
    questions: [
      {
        type: 'date',
        id: 'birthDate',
        question: 'What is your date of birth?',
        required: true,
        onChange: () => {},
      },
      {
        type: 'dropdown',
        id: 'referralSource',
        question: 'How did you hear about us?',
        required: true,
        options: [
          { value: 'google', label: 'Google Search' },
          { value: 'social', label: 'Social Media' },
          { value: 'referral', label: 'Friend/Family Referral' },
          { value: 'doctor', label: 'Healthcare Provider' },
          { value: 'other', label: 'Other' },
        ],
        onChange: () => {},
      },
      {
        type: 'long-text',
        id: 'referralDetails',
        question: 'Please provide any additional details about how you found us',
        description: 'Optional',
        rows: 4,
        onChange: () => {},
      },
    ],
  },
  {
    id: 3,
    title: 'Experience & Preferences',
    description: 'Your experience with care services',
    questions: [
      {
        type: 'yes-no',
        id: 'previousExperience',
        question: 'Have you previously received care services?',
        required: true,
        onChange: () => {},
      },
      {
        type: 'rating',
        id: 'overallWellbeing',
        question: 'On a scale of 0-10, how would you rate your overall wellbeing?',
        description: '0 = Very poor, 10 = Excellent',
        required: true,
        minValue: 0,
        maxValue: 10,
        minLabel: 'Very poor',
        maxLabel: 'Excellent',
        onChange: () => {},
      },
      {
        type: 'scale',
        id: 'stressLevel',
        question: 'What is your current stress level?',
        required: true,
        minValue: 1,
        maxValue: 10,
        minLabel: 'Very low',
        maxLabel: 'Very high',
        onChange: () => {},
      },
    ],
  },
  {
    id: 4,
    title: 'Care Needs',
    description: 'What type of care are you looking for?',
    questions: [
      {
        type: 'single-choice',
        id: 'careType',
        question: 'What type of care are you primarily interested in?',
        required: true,
        choices: [
          { value: 'daycare', label: 'Day Care' },
          { value: 'residential', label: 'Residential Care' },
          { value: 'respite', label: 'Respite Care' },
          { value: 'therapy', label: 'Therapy Services' },
        ],
        onChange: () => {},
      },
      {
        type: 'multiple-choice',
        id: 'activities',
        question: 'Which activities are you interested in?',
        description: 'Select all that apply',
        required: true,
        options: [
          { value: 'animals', label: 'Animal Care & Interaction' },
          { value: 'gardening', label: 'Gardening' },
          { value: 'crafts', label: 'Arts & Crafts' },
          { value: 'sports', label: 'Sports & Physical Activities' },
          { value: 'music', label: 'Music Therapy' },
          { value: 'cooking', label: 'Cooking & Baking' },
        ],
        minSelections: 1,
        maxSelections: 4,
        onChange: () => {},
      },
    ],
  },
  {
    id: 5,
    title: 'Schedule & Availability',
    description: 'When would you like to receive care?',
    questions: [
      {
        type: 'range',
        id: 'ageRange',
        question: 'What age range of participants would you prefer to be with?',
        minValue: 0,
        maxValue: 100,
        step: 5,
        minLabel: '0 years',
        maxLabel: '100 years',
        onChange: () => {},
      },
      {
        type: 'matrix',
        id: 'weeklyAvailability',
        question: 'Please indicate your availability for each day',
        required: true,
        rows: [
          { id: 'monday', label: 'Monday' },
          { id: 'tuesday', label: 'Tuesday' },
          { id: 'wednesday', label: 'Wednesday' },
          { id: 'thursday', label: 'Thursday' },
          { id: 'friday', label: 'Friday' },
        ],
        columns: [
          { id: 'morning', label: 'Morning' },
          { id: 'afternoon', label: 'Afternoon' },
          { id: 'evening', label: 'Evening' },
        ],
        onChange: () => {},
      },
    ],
  },
  {
    id: 6,
    title: 'Health Information',
    description: 'Medical and health details',
    questions: [
      {
        type: 'long-text',
        id: 'medicalHistory',
        question: 'Please describe any relevant medical history or conditions',
        description: 'This information helps us provide better care',
        required: true,
        rows: 6,
        maxLength: 1000,
        onChange: () => {},
      },
      {
        type: 'long-text',
        id: 'medications',
        question: 'Please list any current medications',
        description: 'Include dosage if known',
        rows: 4,
        onChange: () => {},
      },
    ],
  },
  {
    id: 7,
    title: 'Documentation',
    description: 'Upload any relevant documents',
    questions: [
      {
        type: 'file-upload',
        id: 'documents',
        question: 'Upload any relevant medical or identification documents',
        description: 'PDF, images, or Word documents accepted',
        maxFiles: 3,
        maxSizeBytes: 10 * 1024 * 1024,
        acceptedTypes: ['image/*', 'application/pdf', 'application/msword'],
        onChange: () => {},
      },
    ],
  },
  {
    id: 8,
    title: 'Review & Submit',
    description: 'Review your information before submitting',
    questions: [],
  },
];
